name: Publish

on:
  release:
    types: ["published"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: erlef/setup-beam@v1.15.2
        with:
          otp-version: "25.2"
          gleam-version: "0.27.0"
          rebar3-version: "3"
          elixir-version: "1.14.2"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          cd priv
          npm install
          cd ..

      - name: Publish
        run: gleam publish -y
        env:
          HEXPM_USER: ${{ secrets.HEXPM_USER }}
          HEXPM_PASS: ${{ secrets.HEXPM_PASS }}
