name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test-erlang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: erlef/setup-beam@v1.15.2
        with:
          otp-version: "25.2"
          gleam-version: "0.26.1"
          rebar3-version: "3"
          elixir-version: "1.14.2"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test --target erlang

  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: erlef/setup-beam@v1.15.2
        with:
          gleam-version: "0.26.1"
          rebar3-version: "3"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install fast-toml

      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test --target javascript --runtime node

  test-deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: erlef/setup-beam@v1.15.2
        with:
          gleam-version: "0.26.1"
          rebar3-version: "3"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test --target javascript --runtime deno
